---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- hosts: cinder_api
  vars:
    env: "{{ raxmon_environment }}"
    check_name: cinder_api_local_check
    check_details: file={{ check_name }}.pex,args={{ ansible_ssh_host }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'cinder_api_local_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["cinder_api_local_status"] != 1) { return new AlarmStatus(CRITICAL, "API unavailable"); }' }
  user: root
  roles:
    - maas_local

- hosts: cinder_scheduler
  vars:
    env: "{{ raxmon_environment }}"
    check_name: cinder_scheduler_check
    check_details: file=cinder_service_check.pex,args=--host,args={{ ansible_hostname }},args={{ internal_vip_address }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'cinder_scheduler_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["cinder-scheduler_status"] != 1) { return new AlarmStatus(CRITICAL, "cinder-scheduler down"); }' }
  user: root
  roles:
    - maas_local

- hosts: cinder_volume
  vars:
    env: "{{ raxmon_environment }}"
    check_name: cinder_volume_check
    check_details: file=cinder_service_check.pex,args=--host,args={{ ansible_hostname }},args={{ internal_vip_address }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'cinder_volume_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["cinder-volume_status"] != 1) { return new AlarmStatus(CRITICAL, "cinder-volume down"); }' }
  user: root
  roles:
    - maas_local

- hosts: glance_api
  vars:
    env: "{{ raxmon_environment }}"
    check_name: glance_api_local_check
    check_details: file={{ check_name }}.pex,args={{ ansible_ssh_host }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'glance_api_local_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["glance_api_local_status"] != 1) { return new AlarmStatus(CRITICAL, "API unavailable"); }' }
  user: root
  roles:
    - maas_local

- hosts: glance_registry
  vars:
    env: "{{ raxmon_environment }}"
    check_name: glance_registry_local_check
    check_details: file={{ check_name }}.pex,args={{ ansible_ssh_host }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'glance_registry_local_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["glance_registry_local_status"] != 1) { return new AlarmStatus(CRITICAL, "API unavailable"); }' }
  user: root
  roles:
    - maas_local

- hosts: horizon
  vars:
    env: "{{ raxmon_environment }}"
    check_name: horizon_local_check
    check_details: file=horizon_check.pex,args={{ ansible_ssh_host }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'horizon_local_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["horizon_local_status"] != 1) { return new AlarmStatus(CRITICAL, "Horizon unavailable"); }' }
  user: root
  roles:
    - maas_local

- hosts: keystone
  vars:
    env: "{{ raxmon_environment }}"
    check_name: keystone_api_local_check
    check_details: file={{ check_name }}.pex,args={{ ansible_ssh_host }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'keystone_api_local_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["keystone_api_local_status"] != 1) { return new AlarmStatus(CRITICAL, "API unavailable"); }' }
  user: root
  roles:
    - maas_local

- hosts: neutron_server
  vars:
    env: "{{ raxmon_environment }}"
    check_name: neutron_api_local_check
    check_details: file={{ check_name }}.pex,args={{ ansible_ssh_host }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'neutron_api_local_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["neutron_api_local_status"] != 1) { return new AlarmStatus(CRITICAL, "API unavailable"); }' }
  user: root
  roles:
    - maas_local

- hosts: neutron_dhcp_agent
  vars:
    env: "{{ raxmon_environment }}"
    check_name: neutron_dhcp_agent_check
    check_details: file=neutron_service_check.pex,args=--host,args={{ ansible_hostname }},args={{ internal_vip_address }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'neutron_dhcp_agent_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["neutron-dhcp-agent_status"] != 1) { return new AlarmStatus(CRITICAL, "neutron-dhcp-agent down"); }' }
  user: root
  roles:
    - maas_local

- hosts: neutron_l3_agent
  vars:
    env: "{{ raxmon_environment }}"
    check_name: neutron_l3_agent_check
    check_details: file=neutron_service_check.pex,args=--host,args={{ ansible_hostname }},args={{ internal_vip_address }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'neutron_l3_agent_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["neutron-l3-agent_status"] != 1) { return new AlarmStatus(CRITICAL, "neutron-l3-agent down"); }' }
  user: root
  roles:
    - maas_local

- hosts: neutron_metadata_agent
  vars:
    env: "{{ raxmon_environment }}"
    check_name: neutron_metadata_agent_check
    check_details: file=neutron_service_check.pex,args=--host,args={{ ansible_hostname }},args={{ internal_vip_address }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'neutron_metadata_agent_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["neutron-metadata-agent_status"] != 1) { return new AlarmStatus(CRITICAL, "neutron-metadata-agent down"); }' }
  user: root
  roles:
    - maas_local

- hosts: neutron_l3_agent
  vars:
    env: "{{ raxmon_environment }}"
    check_name: neutron_metering_agent_check
    check_details: file=neutron_service_check.pex,args=--host,args={{ ansible_hostname }},args={{ internal_vip_address }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'neutron_metering_agent_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["neutron-metering-agent_status"] != 1) { return new AlarmStatus(CRITICAL, "neutron-metering-agent down"); }' }

- hosts: nova_api_metadata
  vars:
    env: "{{ raxmon_environment }}"
    check_name: nova_api_metadata_local_check
    check_details: file={{ check_name }}.pex,args={{ ansible_ssh_host }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'nova_api_metadata_local_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["nova_api_metadata_local_status"] != 1) { return new AlarmStatus(CRITICAL, "API (metadata) unavailable"); }' }
  user: root
  roles:
    - maas_local

- hosts: nova_api_os_compute
  vars:
    env: "{{ raxmon_environment }}"
    check_name: nova_api_local_check
    check_details: file={{ check_name }}.pex,args={{ ansible_ssh_host }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'nova_api_local_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["nova_api_local_status"] != 1) { return new AlarmStatus(CRITICAL, "API (os-compute) unavailable"); }' }
  user: root
  roles:
    - maas_local

- hosts: nova_compute
  vars:
    env: "{{ raxmon_environment }}"
    check_name: nova_compute_check
    check_details: file=nova_service_check.pex,args=--host,args={{ ansible_hostname }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'nova_compute_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["nova-compute_status"] != 1) { return new AlarmStatus(CRITICAL, "nova-compute down"); }' }
  user: root
  roles:
    - maas_local

- hosts: nova_cert
  vars:
    env: "{{ raxmon_environment }}"
    check_name: nova_cert_check
    check_details: file=nova_service_check.pex,args=--host,args={{ ansible_hostname }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'nova_cert_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["nova-cert_status"] != 1) { return new AlarmStatus(CRITICAL, "nova-cert down"); }' }
  user: root
  roles:
    - maas_local

- hosts: nova_conductor
  vars:
    env: "{{ raxmon_environment }}"
    check_name: nova_conductor_check
    check_details: file=nova_service_check.pex,args=--host,args={{ ansible_hostname }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'nova_conductor_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["nova-conductor_status"] != 1) { return new AlarmStatus(CRITICAL, "nova-conductor down"); }' }
  user: root
  roles:
    - maas_local

- hosts: nova_scheduler
  vars:
    env: "{{ raxmon_environment }}"
    check_name: nova_scheduler_check
    check_details: file=nova_service_check.pex,args=--host,args={{ ansible_hostname }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'nova_scheduler_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["nova-scheduler_status"] != 1) { return new AlarmStatus(CRITICAL, "nova-scheduler down"); }' }
  user: root
  roles:
    - maas_local

- hosts: nova_spice_console
  vars:
    env: "{{ raxmon_environment }}"
    check_name: nova_consoleauth_check
    check_details: file=nova_service_check.pex,args=--host,args={{ ansible_hostname }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'nova_consoleauth_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["nova-consoleauth_status"] != 1) { return new AlarmStatus(CRITICAL, "nova-consoleauth down"); }' }
  user: root
  roles:
    - maas_local

- hosts: nova_spice_console
  vars:
    env: "{{ raxmon_environment }}"
    check_name: nova_spice_console_check
    check_details: file=service_api_local_check.pex,args=nova_spice,args={{ ansible_ssh_host }},args=6082
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'nova_spice_api_local_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["nova_spice_api_local_status"] != 1) { return new AlarmStatus(CRITICAL, "API unavailable"); }' }
  user: root
  roles:
    - maas_local

- hosts: memcached
  vars:
    env: "{{ raxmon_environment }}"
    check_name: memcached_status
    check_details: file={{ check_name }}.pex,args={{ ansible_ssh_host }}
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'memcache_api_local_status', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["memcache_api_local_status"] != 1) { return new AlarmStatus(CRITICAL, "memcached unavailable"); }' }
  user: root
  roles:
    - maas_local

- hosts: hosts
  vars:
    env: "{{ raxmon_environment }}"
    check_name: disk_utilisation
    check_details: file={{ check_name }}.pex
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
    alarms:
      - { 'name': 'percentage_disk_utilisation_sda', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["disk_utilisation_sda"] >= 90.0) { return new AlarmStatus(WARNING, "Disk utilisation for sda >= 90%"); }' }
      - { 'name': 'percentage_disk_utilisation_sdb', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["disk_utilisation_sdb"] >= 90.0) { return new AlarmStatus(WARNING, "Disk utilisation for sdb >= 90%"); }' }
      - { 'name': 'percentage_disk_utilisation_sdc', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (metric["disk_utilisation_sdc"] >= 90.0) { return new AlarmStatus(WARNING, "Disk utilisation for sdc >= 90%"); }' }
  user: root
  roles:
    - maas_local

- hosts: nova_compute
  vars:
    env: "{{ raxmon_environment }}"
    check_name: kvm
    check_details: file={{ check_name }}.pex,args='"kvm=/usr/bin/virsh sysinfo"'
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
  user: root
  roles:
    - maas_local

- hosts: rabbit
  vars:
    env: "{{ raxmon_environment }}"
    check_name: rabbit
    check_details: file={{ check_name }}.pex,args='"rabbit=/usr/sbin/rabbitmqctl list_queues"'
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
  user: root
  roles:
    - maas_local

- hosts: ovs
  vars:
    env: "{{ raxmon_environment }}"
    check_name: rabbit
    check_details: file={{ check_name }}.pex,args='"ovsdb_time=/usr/bin/ovsdb-client list-dbs"',args='"ovsswitchd_time=/usr/bin/ovs-vsctl list-br"'
    check_period: "{{ maas_check_period }}"
    check_timeout: "{{ maas_check_timeout }}"
  user: root
  roles:
    - maas_local
